
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/spring_boot_examples
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  application:
    name: spring-boot-actuator

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      influx:
        uri:
server:
  port: 8080