
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/spring_boot_examples
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  application:
    name: spring-boot-actuator

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      influx:
        uri: http://localhost:8086
        db: springboot
        step: 1s
    web:
      server:
        request:
          autotime:
            enabled: true

server:
  tomcat:
    mbeanregistry:
      enabled: true
  port: 8080

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: example.actuator.domin

